# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default=b'00', max_length=10)),
                ('forward', models.CharField(default=b'+1', max_length=10)),
                ('backward', models.CharField(default=b'00', max_length=10)),
                ('breaker', models.CharField(default=b'00', max_length=10)),
                ('speed', models.CharField(default=b'0km/h', max_length=10)),
                ('total_data', models.CharField(default=b'+100000000', max_length=100)),
            ],
        ),
    ]
